ALTER TABLE bookings ADD COLUMN IF NOT EXISTS confirmed_at DATETIME DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cancellation_reason TEXT DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cancelled_at DATETIME DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS cancelled_by VARCHAR(50) DEFAULT NULL;
